openweather-api:
  url: "http://api.openweathermap.org/data/2.5/weather?q={city}&APPID={appid}"
  timeout: 500
# API token is expected to be passed via a VM argument
#      token:

spring:
  datasource:
    driverClassName: org.postgresql.Driver
# For production having a single connection is a bit risky, so using a connection pool
    hikari:
      connection-timeout: 500
      minimum-idle: 5
      maximum-pool-size: 10
  # Postgres credentials are expected to be passed via VM arguments
#    url
#    username:
#    password:

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
